// Generated by CoffeeScript 1.4.0
(function() {

  require.config({
    paths: {
      base64: 'lib/base64',
      jquery: 'lib/jquery',
      jQuery: 'lib/zooniverse/blanks/jQuery',
      Spine: 'lib/spine',
      Leaflet: 'lib/leaflet',
      leafletProviders: 'lib/leaflet-providers',
      Raphael: 'lib/zooniverse/blanks/Raphael',
      soundManager: 'lib/soundmanager/soundmanager2',
      zooniverse: 'lib/zooniverse'
    },
    shim: {
      base64: {
        exports: 'base64'
      },
      jQuery: {
        deps: ['jquery'],
        exports: function($) {
          $.support.cors = true;
          return $.noConflict();
        }
      },
      Spine: {
        deps: ['jQuery'],
        exports: 'Spine'
      },
      leafletProviders: {
        deps: ['Leaflet'],
        exports: function(Leaflet) {
          return Leaflet;
        }
      },
      Raphael: {
        exports: function() {
          return Raphael;
        }
      },
      soundManager: {
        exports: function() {
          if (window.SM2_DEFER !== true) {
            throw new Error('window.SM2_DEFER must be true before loading SoundManager');
          }
          window.soundManager = new SoundManager();
          window.soundManager.url = 'scripts/lib/soundmanager/swf';
          window.soundManager.preferFlash = true;
          window.soundManager.flashLoadTimeout = 0;
          window.soundManager.html5PollingInterval = 50;
          window.soundManager.debugMode = false;
          window.soundManager.beginDelayedInit();
          return window.soundManager;
        }
      }
    },
    deps: ['site']
  });

}).call(this);
