// Generated by CoffeeScript 1.4.0
(function() {

  define(function(require, exports, module) {
    var $, GoogleAnalytics;
    $ = require('jQuery');
    GoogleAnalytics = (function() {

      GoogleAnalytics.instance = null;

      GoogleAnalytics.track = function(location) {
        return window._gaq.push(['_trackPageview', location || window.location.href]);
      };

      GoogleAnalytics.prototype.account = '';

      GoogleAnalytics.prototype.domain = '';

      function GoogleAnalytics(_arg) {
        var src, _ref;
        this.account = _arg.account, this.domain = _arg.domain;
        if (this.constructor.instance) {
          throw new Error('Google Analytics already instantiated');
        }
        if (!this.account) {
          throw new Error('No account for Google Analytics');
        }
        if (!this.domain) {
          throw new Error('No domain for Google Analytics');
        }
        if ((_ref = window._gaq) == null) {
          window._gaq = [['_setAccount', this.account], ['_setDomainName', this.domain], ['_trackPageview']];
        }
        src = 'http://www.google-analytics.com/ga.js';
        if (location.protocol === 'https:') {
          src = src.replace('http://www', 'https://ssl');
        }
        $("<script src='" + src + "'></script>").appendTo('head');
        $(window).on('hashchange', this.constructor.track);
        this.constructor.track();
        this.constructor.instance = this;
      }

      return GoogleAnalytics;

    })();
    return module.exports = GoogleAnalytics;
  });

}).call(this);
