// Generated by CoffeeScript 1.4.0
(function() {

  describe('Authentication', function() {
    describe('.setSrc', function() {
      it('changes the iframe\'s location', function() {});
      return it('updates the external');
    });
    describe('.post', function() {
      return it('posts a message to the iframe', function() {});
    });
    describe('.logIn', function() {
      return it('triggers a response from the external', function() {});
    });
    return describe('.logOut', function() {
      return it('triggers a response from the external', function() {});
    });
  });

}).call(this);
