// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty;

  define(function(require, exports, module) {
    var Project, Spine;
    Spine = require('Spine');
    Project = (function() {

      Project.prototype.id = '';

      function Project(params) {
        var property, value, workflow, _i, _len, _ref, _ref1;
        if (params == null) {
          params = {};
        }
        for (property in params) {
          if (!__hasProp.call(params, property)) continue;
          value = params[property];
          this[property] = value;
        }
        if ((_ref = this.workflows) == null) {
          this.workflows = [];
        }
        if (!(this.workflows instanceof Array)) {
          this.workflows = [this.workflows];
        }
        _ref1 = this.workflows;
        for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
          workflow = _ref1[_i];
          workflow.project = this;
        }
      }

      return Project;

    })();
    return module.exports = Project;
  });

}).call(this);
