// Generated by CoffeeScript 1.4.0
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(function(require, exports, module) {
    var Spine, Subject, config, joinLines;
    Spine = require('Spine');
    config = require('zooniverse/config');
    joinLines = require('zooniverse/util').joinLines;
    Subject = (function(_super) {

      __extends(Subject, _super);

      Subject.include(Spine.Events);

      Subject.fromJSON = function(raw) {
        return new Subject({
          id: raw.id,
          zooniverseID: raw.zooniverse_id,
          location: raw.location,
          coords: raw.coords,
          metadata: raw.metadata
        });
      };

      Subject.prototype.id = '';

      Subject.prototype.zooniverseID = '';

      Subject.prototype.location = '';

      Subject.prototype.coords = '';

      Subject.prototype.metadata = '';

      function Subject(params) {
        var property, value;
        if (params == null) {
          params = {};
        }
        this.twitterHref = __bind(this.twitterHref, this);

        this.facebookHref = __bind(this.facebookHref, this);

        this.talkHref = __bind(this.talkHref, this);

        for (property in params) {
          if (!__hasProp.call(params, property)) continue;
          value = params[property];
          this[property] = value;
        }
      }

      Subject.prototype.talkHref = function() {
        return "" + config.talkHost + "/objects/" + this.zooniverseID;
      };

      Subject.prototype.facebookHref = function() {
        var text;
        text = "I've classified something on " + config.name + "!";
        return "http://www.facebook.com/sharer.php?u=" + (this.talkHref());
      };

      Subject.prototype.twitterHref = function() {
        var text;
        text = "I've classified something on " + config.name + "!";
        return "https://twitter.com/share?text=" + text + "&url=" + (this.talkHref());
      };

      return Subject;

    }).call(this, Spine.Module);
    return module.exports = Subject;
  });

}).call(this);
