// Generated by CoffeeScript 1.4.0
(function() {

  describe('User', function() {
    describe('.signIn', function() {
      it('does nothing if the user is alreday the current user');
      it('sets the current user', function() {});
      return it('triggers "sign-in" with the new current user');
    });
    describe('.signOut', function() {
      it('destroys the current user', function() {});
      return it('nullifies the current user', function() {});
    });
    it('signs in when Authentication triggers a login', function() {});
    return it('signs out when Authentication triggers a logout', function() {});
  });

}).call(this);
