// Generated by CoffeeScript 1.4.0
(function() {

  define(function(require, exports, module) {
    return module.exports = "<div class=\"content\"></div>\n<div class=\"buttons\"></div>";
  });

}).call(this);
