// Generated by CoffeeScript 1.4.0
(function() {

  define(function(require, exports, module) {
    return '<div class="login-form"></div>\n\n<div class="profile">\n  <section class="favorites">\n    <header>Favorites</header>\n    <p class="none">You haven\'t marked any favorites.</p>\n    <ul>\n      <li>\n        <div class="location"></div>\n      </li>\n    </ul>\n  </section>\n\n  <section class="recents">\n    <header>Recents</header>\n    <p class="none">You haven\'t made any classifications recently.</p>\n    <ul>\n      <li>\n        <div class="location"></div>\n      </li>\n    </ul>\n  </section>\n\n  <section class="groups">\n    <header>Groups</header>\n    <p class="none">You don\'t belong to any groups.</p>\n    <ul>\n      <li>\n        <div class="name"></div>\n      </li>\n    </ul>\n  </section>\n</div>';
  });

}).call(this);
